apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "py-kube-downscaler.labels" . | nindent 4 }}
  name: {{ include "py-kube-downscaler.name" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "py-kube-downscaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "py-kube-downscaler.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "py-kube-downscaler.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        args:
        {{- toYaml .Values.arguments | nindent 8 }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMapName }}
            optional: true
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
