name: Build and push Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print github.ref
        run: echo "Branch ref: ${{ github.ref }}"

      - name: Set tag
        id: set-tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=tags::latest,commit-$SHORT_SHA"
          else
            echo "::set-output name=tags::dev,commit-$SHORT_SHA"
          fi

      - name: Echo set tags
        run: echo "Tags set: ${{ steps.set-tag.outputs.tags }}"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            mtr.devops.telekom.de/caas/py-kube-downscaler
            ghcr.io/caas-team/py-kube-downscaler
          tags: |
            type=raw,value=${{ steps.set-tag.outputs.tags }}

      - name: Echo used tags
        run: echo "Tags being used: ${{ steps.meta.outputs.tags }}"

      # The rest of your steps...
