name: Python Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Test Python
      if: hashFiles('**/*.py') != ''
      uses: lvlcn-t/meta/.github/actions/test-python@main
      with:
        python_version: 3.8
        use_pipenv: "false"
        before_tests: ""
        additional_args: "--cov=tests --cov-report=term-missing:skip-covered"
    - name: Upload pytest coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./coverage.xml
