# https://github.com/marketplace/actions/expire-action
on:
  schedule:
    - cron: "10 6 * * *"

name: Expire container tags

jobs:
  expire-tags:
    runs-on: ubuntu-latest
    name: "expire-tags"
    steps:
      - uses: eumel8/expire-action@1.0.1
        with:
          token: ${{secrets.TAGEXPIRE}}
          repo_type: org
          orgname: caas-team
          image_name: py-kube-downscaler
          protected_tags: sha256:c7df4b1295b2b60b43cbf9116b2c53883e26c8b935b0788564207413e8fa748f
          days_treshold: 60
